spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SEND_FROM_MAIL}
    password: ${SEND_FROM_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  kafka:
    bootstrap-servers: localhost:9092,localhost:9093
    consumer:
      group-id: messaging
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.type.mapping: >
          receipt:com.softserve.messaging.model.UserReceipt,
          validation:com.softserve.messaging.model.UserValidation
    listener:
      missing-topics-fatal: false


server:
  port: 8089
